//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA43Team05B.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueTransaction
    {
        public int TxnID { get; set; }
        public int MemberID { get; set; }
        public int BookID { get; set; }
        public System.DateTime IssueDate { get; set; }
        public System.DateTime DueDate { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public string Remarks { get; set; }
        public string RentalStatus { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Member Member { get; set; }
    }
}
